"""fk repo id

Revision ID: 5f725476606e
Revises: 0e914c6a63a3
Create Date: 2026-03-14 19:01:39.208741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f725476606e'
down_revision: Union[str, Sequence[str], None] = '0e914c6a63a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repo_issue_sync_state_id'), table_name='repo_issue_sync_state')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_repo_issue_sync_state_id'), 'repo_issue_sync_state', ['id'], unique=False)
    # ### end Alembic commands ###
