"""add contributor type

Revision ID: 69a8c175e61f
Revises: 1cda1cde53cc
Create Date: 2026-03-13 19:35:46.834376

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "69a8c175e61f"
down_revision: Union[str, Sequence[str], None] = "1cda1cde53cc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(
        """
        CREATE TYPE contributortype_new AS ENUM ('User', 'Anonymous', 'Bot');
    """
    )

    op.execute(
        """
        ALTER TABLE top_repo_contributors
        ALTER COLUMN type TYPE contributortype_new
        USING (
            CASE type::text
                WHEN 'bot' THEN 'Bot'
                ELSE type::text
            END
        )::contributortype_new
    """
    )

    op.execute("DROP TYPE contributortype")

    op.execute("ALTER TYPE contributortype_new RENAME TO contributortype")

    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
