"""add count columns to repos

Revision ID: 6e8185237603
Revises: 
Create Date: 2026-03-08 14:32:56.746845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e8185237603'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repository', sa.Column('stars_count', sa.Integer(), server_default='0', nullable=False))
    op.alter_column('repository', 'forks_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('repository', 'open_issues_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('repository', 'open_issues_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('repository', 'forks_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('repository', 'stars_count')
    # ### end Alembic commands ###
