"""add cascade rule

Revision ID: 91d98bd3b5be
Revises: 6e8185237603
Create Date: 2026-03-08 15:09:11.082351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91d98bd3b5be'
down_revision: Union[str, Sequence[str], None] = '6e8185237603'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chunk_file_id_fkey'), 'chunk', type_='foreignkey')
    op.drop_constraint(op.f('chunk_chunk_parent_id_fkey'), 'chunk', type_='foreignkey')
    op.create_foreign_key(None, 'chunk', 'file', ['file_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'chunk', 'chunk', ['chunk_parent_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('chunk_embedding_chunk_id_fkey'), 'chunk_embedding', type_='foreignkey')
    op.create_foreign_key(None, 'chunk_embedding', 'chunk', ['chunk_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('documentation_chunk_id_fkey'), 'documentation', type_='foreignkey')
    op.create_foreign_key(None, 'documentation', 'chunk', ['chunk_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('file_module_id_fkey'), 'file', type_='foreignkey')
    op.create_foreign_key(None, 'file', 'module', ['module_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('module_module_parent_id_fkey'), 'module', type_='foreignkey')
    op.create_foreign_key(None, 'module', 'module', ['module_parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'module', type_='foreignkey')
    op.create_foreign_key(op.f('module_module_parent_id_fkey'), 'module', 'module', ['module_parent_id'], ['id'])
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.create_foreign_key(op.f('file_module_id_fkey'), 'file', 'module', ['module_id'], ['id'])
    op.drop_constraint(None, 'documentation', type_='foreignkey')
    op.create_foreign_key(op.f('documentation_chunk_id_fkey'), 'documentation', 'chunk', ['chunk_id'], ['id'])
    op.drop_constraint(None, 'chunk_embedding', type_='foreignkey')
    op.create_foreign_key(op.f('chunk_embedding_chunk_id_fkey'), 'chunk_embedding', 'chunk', ['chunk_id'], ['id'])
    op.drop_constraint(None, 'chunk', type_='foreignkey')
    op.drop_constraint(None, 'chunk', type_='foreignkey')
    op.create_foreign_key(op.f('chunk_chunk_parent_id_fkey'), 'chunk', 'chunk', ['chunk_parent_id'], ['id'])
    op.create_foreign_key(op.f('chunk_file_id_fkey'), 'chunk', 'file', ['file_id'], ['id'])
    # ### end Alembic commands ###
