"""init

Revision ID: a88df20f9431
Revises: 
Create Date: 2026-03-25 10:06:37.529718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a88df20f9431'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_issue_assignee_github_user_id'), table_name='issue_assignee')
    op.create_index(op.f('ix_issue_assignee_github_user_id'), 'issue_assignee', ['github_user_id'], unique=False)
    op.create_unique_constraint('uq_issue_assignee_issue_user', 'issue_assignee', ['issue_id', 'github_user_id'])
    op.add_column('user', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('user', sa.Column('points', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('level', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'level')
    op.drop_column('user', 'points')
    op.drop_column('user', 'avatar_url')
    op.drop_constraint('uq_issue_assignee_issue_user', 'issue_assignee', type_='unique')
    op.drop_index(op.f('ix_issue_assignee_github_user_id'), table_name='issue_assignee')
    op.create_index(op.f('ix_issue_assignee_github_user_id'), 'issue_assignee', ['github_user_id'], unique=True)
    # ### end Alembic commands ###
