"""comments constraints

Revision ID: b6726f03b52a
Revises: e0b00ab2c65a
Create Date: 2026-03-25 09:43:36.354724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b6726f03b52a'
down_revision: Union[str, Sequence[str], None] = 'e0b00ab2c65a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issue_label')
    op.drop_index(op.f('ix_issue_comment_github_user_id'), table_name='issue_comment')
    op.create_unique_constraint(None, 'issue_comment', ['github_user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'issue_comment', type_='unique')
    op.create_index(op.f('ix_issue_comment_github_user_id'), 'issue_comment', ['github_user_id'], unique=True)
    op.create_table('issue_label',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('issue_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issue.id'], name=op.f('issue_label_issue_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('issue_label_pkey'))
    )
    # ### end Alembic commands ###
