"""comments constraints

Revision ID: cb3cacca7846
Revises: b6726f03b52a
Create Date: 2026-03-25 09:46:41.577043

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cb3cacca7846"
down_revision: Union[str, Sequence[str], None] = "b6726f03b52a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("issue_comment_github_user_id_key"), "issue_comment", type_="unique"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("issue_comment_github_user_id_key"),
        "issue_comment",
        ["github_user_id"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
