"""comments table

Revision ID: d1be58b2d553
Revises: ea0c9209dec9
Create Date: 2026-03-16 18:54:21.263131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1be58b2d553'
down_revision: Union[str, Sequence[str], None] = 'ea0c9209dec9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_repo_issue_number', 'issue', ['repository_id', 'number'])
    op.add_column('issue_comment', sa.Column('github_comment_id', sa.BigInteger(), nullable=False))
    op.add_column('issue_comment', sa.Column('github_user_id', sa.BigInteger(), nullable=False))
    op.add_column('issue_comment', sa.Column('username', sa.String(), nullable=False))
    op.add_column('issue_comment', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('issue_comment', sa.Column('posted_at', sa.DateTime(), nullable=False))
    op.add_column('issue_comment', sa.Column('body', sa.String(), nullable=False))
    op.create_index(op.f('ix_issue_comment_github_comment_id'), 'issue_comment', ['github_comment_id'], unique=True)
    op.create_index(op.f('ix_issue_comment_github_user_id'), 'issue_comment', ['github_user_id'], unique=True)
    op.drop_column('issue_comment', 'next_cursor')
    op.drop_column('issue_comment', 'num_of_comments')
    op.drop_column('issue_comment', 'is_fully_synced')
    op.drop_column('issue_comment', 'is_refreshing')
    op.drop_column('issue_comment', 'last_error')
    op.add_column('repo_issue_sync_state', sa.Column('num_of_comments', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repo_issue_sync_state', 'num_of_comments')
    op.add_column('issue_comment', sa.Column('last_error', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('issue_comment', sa.Column('is_refreshing', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('issue_comment', sa.Column('is_fully_synced', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('issue_comment', sa.Column('num_of_comments', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('issue_comment', sa.Column('next_cursor', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_issue_comment_github_user_id'), table_name='issue_comment')
    op.drop_index(op.f('ix_issue_comment_github_comment_id'), table_name='issue_comment')
    op.drop_column('issue_comment', 'body')
    op.drop_column('issue_comment', 'posted_at')
    op.drop_column('issue_comment', 'avatar_url')
    op.drop_column('issue_comment', 'username')
    op.drop_column('issue_comment', 'github_user_id')
    op.drop_column('issue_comment', 'github_comment_id')
    op.drop_constraint('uq_repo_issue_number', 'issue', type_='unique')
    # ### end Alembic commands ###
