"""fix num of comments

Revision ID: e0b00ab2c65a
Revises: d1be58b2d553
Create Date: 2026-03-17 14:12:16.124386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0b00ab2c65a'
down_revision: Union[str, Sequence[str], None] = 'd1be58b2d553'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issue', sa.Column('num_of_comments', sa.Integer(), server_default='0', nullable=False))
    op.drop_column('repo_issue_sync_state', 'num_of_comments')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repo_issue_sync_state', sa.Column('num_of_comments', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_column('issue', 'num_of_comments')
    # ### end Alembic commands ###
