"""add repo stats

Revision ID: e1330a8c77f1
Revises: 91d98bd3b5be
Create Date: 2026-03-11 15:00:40.101389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1330a8c77f1'
down_revision: Union[str, Sequence[str], None] = '91d98bd3b5be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('top_repo_contributors', sa.Column('name', sa.String(), nullable=False))
    op.add_column('top_repo_contributors', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('top_repo_contributors', sa.Column('num_of_contributions', sa.Integer(), nullable=False))
    op.add_column('top_repo_contributors', sa.Column('type', sa.Enum('User', 'Anonymous', name='contributortype'), nullable=False))
    op.drop_column('top_repo_contributors', 'num_of_closed_issues')
    op.drop_column('top_repo_contributors', 'num_of_merged_pr')
    op.drop_column('top_repo_contributors', 'num_of_contributors')
    op.drop_column('top_repo_contributors', 'num_of_commits')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('top_repo_contributors', sa.Column('num_of_commits', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('top_repo_contributors', sa.Column('num_of_contributors', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('top_repo_contributors', sa.Column('num_of_merged_pr', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('top_repo_contributors', sa.Column('num_of_closed_issues', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_column('top_repo_contributors', 'type')
    op.drop_column('top_repo_contributors', 'num_of_contributions')
    op.drop_column('top_repo_contributors', 'avatar_url')
    op.drop_column('top_repo_contributors', 'name')
    # ### end Alembic commands ###
