"""issue labels

Revision ID: e819b573c442
Revises: e0b00ab2c65a
Create Date: 2026-03-19 03:55:11.023760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e819b573c442'
down_revision: Union[str, Sequence[str], None] = 'e0b00ab2c65a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issue_label', sa.Column('description', sa.String(), nullable=False))
    op.add_column('issue_label', sa.Column('color', sa.String(), nullable=False))
    op.drop_index(op.f('ix_issue_label_github_user_id'), table_name='issue_label')
    op.drop_column('issue_label', 'body')
    op.drop_column('issue_label', 'avatar_url')
    op.drop_column('issue_label', 'github_user_id')
    op.drop_column('issue_label', 'posted_at')
    op.drop_column('issue_label', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issue_label', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('issue_label', sa.Column('posted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('issue_label', sa.Column('github_user_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('issue_label', sa.Column('avatar_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('issue_label', sa.Column('body', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_issue_label_github_user_id'), 'issue_label', ['github_user_id'], unique=True)
    op.drop_column('issue_label', 'color')
    op.drop_column('issue_label', 'description')
    # ### end Alembic commands ###
