"""remove last synced

Revision ID: ea0c9209dec9
Revises: a825b389af43
Create Date: 2026-03-14 19:53:02.780110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea0c9209dec9'
down_revision: Union[str, Sequence[str], None] = 'a825b389af43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repo_issue_sync_state', 'last_full_sync_at')
    op.drop_column('repo_issue_sync_state', 'last_synced_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repo_issue_sync_state', sa.Column('last_synced_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('repo_issue_sync_state', sa.Column('last_full_sync_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
