REPOS_PATH = "repos"


SKIP_EXT = {
    ".png",
    ".jpg",
    ".jpeg",
    ".gif",
    ".webp",
    ".ico",
    ".pdf",
    ".zip",
    ".tar",
    ".gz",
    ".7z",
    ".rar",
    ".mp4",
    ".mov",
    ".avi",
    ".mp3",
    ".wav",
    ".exe",
    ".dll",
    ".so",
    ".dylib",
    ".bin",
    ".class",
    ".jar",
}

SKIP_DIR_MARKERS = {
    "node_modules",
    "dist",
    "build",
    ".next",
    ".nuxt",
    ".git",
    ".idea",
    ".vscode",
    "coverage",
    ".venv",
    "venv",
    "__pycache__",
    ".pytest_cache",
    "vendor",
    "target",
}

IMPORTANT_FILES_EXACT = {
    "readme.md",
    "readme.rst",
    "readme.txt",
    "license",
    "license.md",
    "license.txt",
    "contributing.md",
    "code_of_conduct.md",
    "security.md",
    "changelog.md",
    "pyproject.toml",
    "requirements.txt",
    "poetry.lock",
    "package.json",
    "pnpm-lock.yaml",
    "yarn.lock",
    "dockerfile",
    "compose.yml",
    "compose.yaml",
    ".env.example",
}

IMPORTANT_PREFIXES = (
    "docs/",
    ".github/",
    "src/",
    "app/",
    "lib/",
    "packages/",
)


AST_LANG_EXT = {
    ".py",
    ".js",
    ".jsx",
    ".ts",
    ".tsx",
    ".java",
    ".kt",
    ".go",
    ".c",
    ".cpp",
    ".cs",
    ".php",
    ".swift",
}

TEXT_LANG_EXT = {
    ".md",
    ".rst",
    ".txt",
    ".yml",
    ".yaml",
    ".json",
    ".toml",
    ".ini",
    ".cfg",
    ".html",
    ".css",
    ".scss",
    ".sh",
}

BINARY_FILE_MAGICS = {
    b"\x89PNG\r\n\x1a\n",
    b"\xff\xd8\xff",
    b"GIF87a",
    b"GIF89a",
    b"BM",
    b"RIFF",
    b"%PDF",
    b"\xd0\xcf\x11\xe0\xa1\xb1\x1a\xe1",
    b"PK\x03\x04",
    b"{\\rtf",
    b"\x1f\x8b",
    b"BZh",
    b"\xfd7zXZ",
    b"7z\xbc\xaf\x27\x1c",
    b"Rar!",
    b"MZ",
    b"\x7fELF",
    b"\xcf\xfa\xed\xfe",
    b"\xca\xfe\xba\xbe",
    b"\xfe\xed\xfa\xce",
    b"\xfe\xed\xfa\xcf",
    b"OggS",
    b"ID3",
    b"fLaC",
    b"\x00\x00\x00\x18ftyp",
    b"\x00\x00\x00 ftyp",
    b"\x00\x01\x00\x00",
    b"OTTO",
    b"wOFF",
    b"wOF2",
    b"SQLite format 3\x00",
}
